name: GATSBY BUILD

on:
  push:
    branches: [master]
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
          
      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            server: ${{ secrets.SSH_HOST }}
            port: 222
            local_path: 'public/*'
            remote_path: '/home/crkikweqem/domains/springstudio.pl/public_html/'
            sftp_only: true
